<?php

/**
 * @file
 * Functions to support theming in the cassiopeiatheme theme.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Link;
use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Xss;
use Drupal\node\Entity\Node;
use Drupal\Component\Render\MarkupInterface;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function cassiopeiatheme_preprocess_html(&$variables) {
  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }

//  $path =  \Drupal::service('extension.list.module')->getPath('cassiopeiatheme');
//  print_r($path);
}


/**
 * Implements hook_page_attachments_alter() for page templates.
 */
function cassiopeiatheme_page_attachments_alter(&$page) {

}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function cassiopeiatheme_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function cassiopeiatheme_preprocess_page_title(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for maintenance-page.html.twig.
 */
function cassiopeiatheme_preprocess_maintenance_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function cassiopeiatheme_preprocess_node(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for region.html.twig.
 */
function cassiopeiatheme_preprocess_region(&$variables) {


}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function cassiopeiatheme_preprocess_block(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for form elements.
 */
function cassiopeiatheme_preprocess_form_element(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for form-element-label.html.twig.
 */
function cassiopeiatheme_preprocess_form_element_label(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function cassiopeiatheme_preprocess_menu(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-task.html.twig.
 */
function cassiopeiatheme_preprocess_menu_local_task(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-tasks.html.twig.
 */
function cassiopeiatheme_preprocess_menu_local_tasks(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiatheme_theme_suggestions_menu_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-action.html.twig.
 */
function cassiopeiatheme_preprocess_menu_local_action(&$variables) {

}

/**
 * Implements template_preprocess_table()
 */
function cassiopeiatheme_preprocess_table(&$variables) {

}

/**
 * Implements template_preprocess_views_view_table()
 */
function cassiopeiatheme_preprocess_views_view_table(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for region templates.
 */
function cassiopeiatheme_theme_suggestions_region_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiatheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiatheme_theme_suggestions_user_alter(array &$suggestions, array $variables, $hook) {


  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for page template.
 */
function cassiopeiatheme_theme_suggestions_page_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_HOOK_form_alter() for node add/edit.
 */
function cassiopeiatheme_form_node_form_alter(&$form, FormStateInterface $form_state) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for links templates.
 */
function cassiopeiatheme_theme_suggestions_links_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for status messages templates.
 */
function cassiopeiatheme_theme_suggestions_status_messages_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess_HOOK() for breadcrumb.
 */
function cassiopeiatheme_preprocess_breadcrumb(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for status_messages.
 */
function cassiopeiatheme_preprocess_status_messages(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function cassiopeiatheme_theme_suggestions_form_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function cassiopeiatheme_theme_suggestions_input_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess().
 */
function cassiopeiatheme_preprocess(&$variables, $hook) {

}

/**
 * Implements hook_preprocess_input() for adding classes to inputs.
 */
function cassiopeiatheme_preprocess_input(&$variables) {

}

/**
 * Implements hook_preprocess_select() for adding classes to select boxes.
 */
function cassiopeiatheme_preprocess_select(&$variables) {

}
