<?php

/**
 * @file
 * Functions to support theming in the cassiopeiaadmintheme theme.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Link;
use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Xss;
use Drupal\node\Entity\Node;
use Drupal\Component\Render\MarkupInterface;


use Drupal\Component\Uuid\Uuid;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function cassiopeiaadmintheme_preprocess_html(&$variables) {
  if (isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = array_merge($variables['attributes']['class'],['layout-fixed', 'sidebar-expand-lg', 'bg-body-tertiary']);
  }else {
    $variables['attributes']['class'] = ['layout-fixed', 'sidebar-expand-lg', 'bg-body-tertiary'];
  }

//  $path =  \Drupal::service('extension.list.module')->getPath('cassiopeiaadmintheme');
//  print_r($path);
}


/**
 * Implements hook_page_attachments_alter() for page templates.
 */
function cassiopeiaadmintheme_page_attachments_alter(&$page) {

}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function cassiopeiaadmintheme_preprocess_page(&$variables) {

  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('cassiopeia_admin')) {
    $administrator_menu = \Drupal::service('cassiopeia_admin.administrator')->cassiopeia_admin_get_administrator_menu();
    $variables['administrator_menu'] = $administrator_menu;
  }
//  $user = \Drupal\user\Entity\User::load(1);
//  dump($user->toArray());
//  dump($user->get('user_picture')->entity->getFileUri());
//  $node = \Drupal\node\Entity\Node::load(1);
//  dump($node->get('field_image')->entity->getFileUri());

//  $user_picture = $user->user_picture->entity->getFileUri();
//  print_r($user_picture);
//  $file = \Drupal\file\Entity\File::load(2);
//  dump($file->getFileUri());
//  getFileUri

//  Todo
//  $styles = \Drupal\image\Entity\ImageStyle::loadMultiple();
//  $styles = \Drupal::entityTypeManager()->getStorage('image_style')->loadMultiple();
//  dump($styles);

//  End todo

}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function cassiopeiaadmintheme_preprocess_page_title(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for maintenance-page.html.twig.
 */
function cassiopeiaadmintheme_preprocess_maintenance_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function cassiopeiaadmintheme_preprocess_node(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for region.html.twig.
 */
function cassiopeiaadmintheme_preprocess_region(&$variables) {


}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function cassiopeiaadmintheme_preprocess_block(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for form elements.
 */
function cassiopeiaadmintheme_preprocess_form_element(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for form-element-label.html.twig.
 */
function cassiopeiaadmintheme_preprocess_form_element_label(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function cassiopeiaadmintheme_preprocess_menu(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-task.html.twig.
 */
function cassiopeiaadmintheme_preprocess_menu_local_task(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-tasks.html.twig.
 */
function cassiopeiaadmintheme_preprocess_menu_local_tasks(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiaadmintheme_theme_suggestions_menu_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess_HOOK() for menu-local-action.html.twig.
 */
function cassiopeiaadmintheme_preprocess_menu_local_action(&$variables) {
  $variables['link']['#options']['attributes']['class'][] = 'btn-sm';
}

/**
 * Implements template_preprocess_table()
 */
function cassiopeiaadmintheme_preprocess_table(&$variables) {

}

/**
 * Implements template_preprocess_views_view_table()
 */
function cassiopeiaadmintheme_preprocess_views_view_table(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for region templates.
 */
function cassiopeiaadmintheme_theme_suggestions_region_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiaadmintheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cassiopeiaadmintheme_theme_suggestions_user_alter(array &$suggestions, array $variables, $hook) {


  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for page template.
 */
function cassiopeiaadmintheme_theme_suggestions_page_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_HOOK_form_alter() for node add/edit.
 */
function cassiopeiaadmintheme_form_node_form_alter(&$form, FormStateInterface $form_state) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for links templates.
 */
function cassiopeiaadmintheme_theme_suggestions_links_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for status messages templates.
 */
function cassiopeiaadmintheme_theme_suggestions_status_messages_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess_HOOK() for breadcrumb.
 */
function cassiopeiaadmintheme_preprocess_breadcrumb(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for status_messages.
 */
function cassiopeiaadmintheme_preprocess_status_messages(&$variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function cassiopeiaadmintheme_theme_suggestions_form_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function cassiopeiaadmintheme_theme_suggestions_input_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_preprocess().
 */
function cassiopeiaadmintheme_preprocess(&$variables, $hook) {

}

/**
 * Implements hook_preprocess_input() for adding classes to inputs.
 */
function cassiopeiaadmintheme_preprocess_input(&$variables) {

}

/**
 * Implements hook_preprocess_select() for adding classes to select boxes.
 */
function cassiopeiaadmintheme_preprocess_select(&$variables) {

}
